workflows:
  android-apk:
    name: Gerar APK Pg Final
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Instalar Dependencias e Capacitor
        script: |
          npm install
          npm install @capacitor/android
      - name: Build do Projeto Web
        script: npm run build
      - name: Criar Pasta Android e Sincronizar
        script: |
          npx cap add android || true
          npx cap copy android
          npx cap sync android
      - name: Liberar Acesso a Internet e Sites Externos
        script: |
          # 1. Adiciona permissão de Internet
          sed -i '' '/<application/i \
          <uses-permission android:name="android.permission.INTERNET" />' android/app/src/main/AndroidManifest.xml
          
          # 2. Força o Android a aceitar tráfego de sites de notícias (HTTP/HTTPS)
          sed -i '' 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
      - name: Gerar APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - lazarosetton@gmail.com 
